name: "action-semantic-release"
description: "Automatically release a new version on GitHub"
inputs:
  docker-username:
    description: "The username for the docker account used to publish"
    required: true
    default: "default"
  docker-token:
    description: "The token for the docker account used to publish"
    required: true
    default: "default"
  image-name:
    description: "The name (repository) of the image being published"
    required: true
    default: "default"
  image-tag:
    description: "The tag of the image being published"
    required: true
    default: "latest"
  dry-run:
    description: "Flag for whether to actually publish the image"
    required: false
    default: false
outputs:
  tag:
    description: "The tag that was published"
  sha-tag:
    description: "The sha-specific tag that was published"
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker login
      run: docker login -u ${{inputs.docker-username}} -p ${{docker-token}}
    - name: Build short tag
      run: docker build -t ${{inputs.image-name}}:${{inputs.image-tag}} .
      shell: bash
    - name: Build sha tag
      run: docker build -t ${{inputs.image-name}}:${{inputs.image-tag}}--$(git rev-parse --short HEAD) .
      shell: bash
    - name: Push short tag
      if: ${{ ! inputs.dry-run}}
      run: docker image push ${{inputs.image-name}}:${{inputs.image-tag}}
      shell: bash
    - name: Push sha tag
      if: ${{ ! inputs.dry-run}}
      run: docker image push ${{inputs.image-name}}:${{inputs.image-tag}}--$(git rev-parse --short HEAD)
      shell: bash
    - name: Set output
      id: set-output
      run: echo "### Published tags: $tag; $sha_tag" >> $GITHUB_STEP_SUMMARY
      shell: bash
