name: "action-semantic-release"
description: "Automatically release a new version on GitHub"
inputs:
  docker-username:
    description: "The username for the docker account used to publish"
    required: true
  docker-token:
    description: "The token for the docker account used to publish"
    required: true
  image-name:
    description: "The name (repository) of the image being published"
    required: true
  image-tag:
    description: "The tag of the image being published"
    required: true
  dry-run:
    description: "Flag for whether to actually publish the image"
    required: false
    default: "false"
  publish-latest:
    description: "Flag for whether to publish the image with the 'latest' flag"
    required: false
    default: "false"
outputs:
  tag:
    description: "The tag that was published"
  sha-tag:
    description: "The sha-specific tag that was published"
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker login
      run: docker login -u ${{inputs.docker-username}} -p ${{inputs.docker-token}}
      shell: bash
    - name: Build short tag
      run: docker build -t ${{inputs.image-name}}:${{inputs.image-tag}} .
      shell: bash
    - name: Build sha tag
      run: docker build -t ${{inputs.image-name}}:${{inputs.image-tag}}--$(git rev-parse --short HEAD) .
      shell: bash
    - name: Build latest tag
      if: ${{ inputs.publish-latest == "true" }}
      run: docker build -t latest .
      shell: bash
    - name: Push short tag
      if: ${{ inputs.dry-run == "false" }}
      run: docker image push ${{inputs.image-name}}:${{inputs.image-tag}}
      shell: bash
    - name: Push sha tag
      if: ${{ inputs.dry-run == "false" }}
      run: docker image push ${{inputs.image-name}}:${{inputs.image-tag}}--$(git rev-parse --short HEAD)
      shell: bash
    - name: Push latest tag
      if: ${{ inputs.publish-latest == "true" }}
      run: docker image push latest
      shell: bash
