name: Release Action
permissions: read-all
on:
  push:
    branches:
      - main
      - beta
      - dev
      - staging
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    name: Semantic Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        uses: outoforbitdev/action-semantic-release@v1.3.5
        id: semanticrelease
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
      - name: Get the output time
        run: echo "The time was ${{ steps.semanticrelease.outputs.time}}"
