name: Release Action
permissions: read-all
on:
  push:
    branches:
      - main
      - beta
      - dev
      - staging
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Publish Image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Publish Image
        uses: ./
        id: dockerpublish
        with:
          dockerfile-path: ./.test
          docker-username: ${{ vars.DOCKER_USERNAME }}
          docker-token: ${{ secrets.DOCKER_TOKEN }}
          image-name: ${{ vars.IMAGE_NAME }}
          image-tag: test-tag
          publish-latest: true
          build-args: |
            EXAMPLE="example"
            OTHER_EXAMPLE="another_example"
  release:
    runs-on: ubuntu-latest
    name: Publish Release
    needs: test
    outputs:
      versionReleased: ${{steps.semanticrelease.outputs.version-released}}
      version: ${{steps.semanticrelease.outputs.next-version}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Semantic Release
        uses: outoforbitdev/action-semantic-release@v1.6.0
        id: semanticrelease
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          skip-changelog: ${{ github.ref_name != 'main' }}
