name: Release Action
permissions: read-all
on:
  push:
    branches:
      - main
      - beta
      - dev
      - staging
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    name: Publish Release
    outputs:
      versionReleased: ${{steps.semanticrelease.outputs.version-released}}
      version: ${{steps.semanticrelease.outputs.next-version}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Semantic Release
        uses: outoforbitdev/action-semantic-release@v1.3.6
        id: semanticrelease
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
