name: Test Action
permissions: read-all
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Publish Image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Publish Image
        uses: ./
        id: dockerpublish
        with:
          docker-username: ${{ vars.DOCKER_USERNAME }}
          docker-token: ${{ secrets.DOCKER_TOKEN }}
          image-name: ${{ vars.IMAGE_NAME }}
          image-tag: test-tag
          publish-latest: true
          # build-args: >-
          #   --build-arg EXAMPLE="example"
          #   --build-arg OTHER_EXAMPLE="another_example"
