name: Test Release
permissions: read-all
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - beta
      - dev
      - staging
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    name: Test Release
    outputs:
      versionReleased: ${{steps.semanticrelease.outputs.version-released}}
      version: ${{steps.semanticrelease.outputs.next-version}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Semantic Release
        uses: outoforbitdev/action-semantic-release@v1.3.5
        id: semanticrelease
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          dry-run: true
